<MainWindow>:
    orientation: "horizontal"
    ListView:
        width: 200
        size_hint_x: None
    BoxLayout:
        orientation: "vertical"
        ListView:
        TextInput:
            size_hint_y: None
            font_size: sp(16)
            multiline: False
            height: self.font_size + sp(5)
    BoxLayout:
        orientation: "vertical"
        width: 200
        size_hint_x: None
        Button:
            background_color: 1, 0, 0